[package]
name = "zero-to-production"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
anyhow = "1.0.70"
dotenvy = "0.15.7"
lazy_static = "1.4.0"

